language: php
php:
- 5.5
- 5.6
- 7.0
- hhvm
matrix:
  fast_finish: true
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
script:
- cd $TRAVIS_BUILD_DIR
- if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then vendor/bin/phpunit -c test/phpunit.xml --coverage-clover=./build/clover.xml; else vendor/bin/phpunit -c test/phpunit.xml; fi
- vendor/bin/phpcs --standard=PSR2 -s -p src/
after_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then wget https://scrutinizer-ci.com/ocular.phar;
  php ocular.phar code-coverage:upload build/clover.xml --format=php-clover; fi
notifications:
  slack:
    secure: BwOJtUXTnEV/eGfIo0PipHoQKy65t6Md1kDZ0XJvQqy/XtkaxCBf0ieVOlHVpzJ9hYiGFSl6m9uvA8UYaKwZSRFuubVfjobo2wUhvRztlqgUBlYmDegNKyepIoteUxxNjrn1crweCyePbRDFQZfYV2WE9xKI0A+sYePcnYC3ZPpkmpZ9PMnTtgetHyutmI4x14EBe93A4FUUgUDKX13oGqOlYjS0yCzoUHFwn4ETWOnnTktXJEYb/Elmg6rY//P7Zepk82jv7qJ9iQoaIPrMFPuy2QxYEuf28ZkcNEyGsc/3rDy6/80t+m6MNXUDh0MZMlFrFeIuFmI+z9NeIUi9pmVpRCbZGtTaRIbcMyurXSKv/CSPhbgMjR/i8eObgebGOZ9BY6uh/QMWg8jynsqifI3Lh4MALH+J6hjShipsUUH5z1STg82dM8Qv8oVcWBgkJhQhHslJk9JDlMf/wubDJEJcZwP/TklWO507LLA84PEzEH3sAl6YNUv8e+NYFoeLIG4U5iEsmX/lYduSjR/TAL6We+6saFAWNIgQLph1Qyv86W2YCFBFGfsF9UTP0XYgtR5zu4zMXrj31OoUigL3EbzCzypr9EAD6iu5A21V4DbC+WmpCQfWFW6JdgFBiw4G31AFlv56G/tQl5ZMoVd77aBn0muOqkhkGSfcZHWhPfU=
