site_name: Tonis
site_author: Kyle Spraggs
copyright: '&copy; 2015 Kyle Spraggs. All Rights Reserved.'
site_url: http://docs.tonis.io
repo_url: https://github.com/tonis-io/tonis/
theme: readthedocs
pages:
- Home: 'index.md'
- Getting Started:
  - getting-started/installing.md
  - getting-started/hello-world.md
  - getting-started/contributing.md
  - getting-started/license.md
- Basics:
  - basics/routing.md
  - basics/middleware.md
- Resources:
  - 'Official Middleware': resources/official-middleware.md
